### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/SalaryPaycheckPaulo#1]
Hi @PauloRenato4!

Your README.md is outdated and it do not reflect the language used in your exam.

![image](https://cloud.githubusercontent.com/assets/5324414/10768030/3cee2b98-7cc6-11e5-9b64-9f2a1744a041.png)

**Comment by PauloRenato4** [comment]
https://github.com/univas-first-exam/SalaryPaycheckPaulo/blob/master/README.md
