### ISSUE TITLE
Method names

### ISSUE THREAD

**Issue by edysegura** [univas-first-exam/SalaryPaycheckPaulo#2]
These method names doesn't have any semantic meaning for this application.

![image](https://cloud.githubusercontent.com/assets/5324414/10768118/abae4734-7cc6-11e5-8e2e-3bb9d8110200.png)

**Comment by PauloRenato4** [comment]
https://github.com/univas-first-exam/SalaryPaycheckPaulo/blob/master/assent/js/salaryService.js

**Comment by edysegura** [comment]
Much better!! Thank you!
